djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^save_data/$', views.save_data, name="save_data"),
]

djangonautic/djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^signup/$', views.signup),
    url(r'^$', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class IntakeItems(models.Model):
    divString = models.TextField(blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return self.divString

djangonautic/accounts/forms.py
from django import forms
from . import models

class CreateItems(forms.ModelForm):
    class Meta:
        model = models.IntakeItems
        fields = ['divString']

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log the user in
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect('home')
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

@login_required(login_url="/accounts/login/")
def save_data(request):
    if request.method == 'POST':
        form = forms.CreateItems(request.POST, request.FILES)
        #print(form)
        #print(form.errors)
        if form.is_valid():
            #print(form.divString)
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('home')
    else:
        form = forms.CreateItems()
    return render(request, '', {'form': form})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'base_layout.html')

def signup(request):
    # return HttpResponse('about')
    return render(request, 'signup_layout.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'signup_layout.html' %}

{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" name="" value="Login">
  </form>
{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'signup_layout.html' %}

{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="" value="Signup">
  </form>
{% endblock %}

djangonautic/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Caffeine Buddy</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--Bootstrap CSS, Graph.js-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

    <!-- import the webpage's stylesheet/js file -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-expand-sm navbar-light bg-light shadow-sm p-3 mb-1">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link navLinkStyle navStyleClicked" id="myCaffeinePg">My Caffeine</a>
          <a class="nav-item nav-link navLinkStyle" id="trendsPg">Trends</a>
          <a class="nav-item nav-link navLinkStyle" id="myAccountPg" href="/accounts/login">My Account</a>
        </div>
      </div>
      <ul class="navbar-nav ml-auto">
          <img src="https://cdn.glitch.com/d959f5b2-4107-480c-a30a-4ab5f8968f79%2Fcoffee_cup%20(2).png?1558547562811" alt="coffee cup" height="50px">
      </ul>
    </nav>
    <div class="container">
      <div class="row" id="myCaffeineRow">
        <div class="col-md-5 m-1 mt-5">
          <input type="date" placeholder="Date" class="mb-2 shadow" id="currentDate">
          <div class="shadow">
            <ul class="list-group" id="intakeList">
              {% if user.is_authenticated %}
                {% block content %}
                  {{ divIntakeList.divString }}
                {% endblock %}
              {% else %}
                <li class="list-group-item container" id="intakeItem0">
                <div class="row">
                  <div class="col-6 pr-1 mr-3">
                    <input type="text" placeholder="Drink" class="intakeText smallWidth" >
                  </div>
                  <div class="col-1 pt-2 pl-0 pr-0">
                    <input type="number" class="smallInput boldText" id="caffeineAmount">
                  </div>
                  <div class="col-4 pt-2 pl-1 pr-0">
                    <small class="smallWrap">mg caffeine per quanitity</small>
                  </div>
                </div>

                <div class="row mt-2 mb-1">
                  <div class="col">
                    <small class="mb-0">Quantity</small>
                  </div>
                  <div class="col ">
                    <small class="mb-0">Time</small>
                  </div>
                </div>

                <div class="row">
                  <div class="col-2 pr-0">
                    <input type="number" class="smallInput smallWidth quantityInput" id="intakeQuantity">
                  </div>
                  <div class="col-3 pr-0 pl-0">
                    <select id="intakeUnits">
                      <option value="cups">cups</option>
                      <option value="oz">oz</option>
                      <option value="ml">ml</option>
                    </select>
                  </div>
                  <div class="col-1 pl-0">

                  </div>
                  <div class="col-3">
                    <input type="time" id="intakeTime">
                  </div>
                  <div class="col-3">
                    <button type="button" class="btn btn-danger ml-1">X</button>
                  </div>
                </div>
              </li>
              {% endif %}
            </ul>
          </div>
          <!--<form class="" action="{% url 'accounts:save_data' %}" method="post">-->
            <!--{% csrf_token %}-->
            <input type="text" id="id_divString" style="display:none">
            <button class="btn btn-outline-primary mt-2 shadow" onclick="handlers.addIntake()">Add Intake</button>
          <!--</form>-->
        </div>
        <div class="col-12 mt-5 ">
          <h5>Bodily Caffeine Levels</h5>
        </div>
        <div class="col-md-6 m-1  shadow">
            <canvas id="myChart"></canvas>
        </div>
      </div>
      <div class="row" id="trendsRow" style="display:none">
        <div class="col-6 mt-5 mb-1">
          <h5>From</h5><input type="date" placeholder="Date" class="mb-2 shadow" id="trendsDate0">
        </div>
        <div class="col-6 mt-5 mb-1">
          <h5>To</h5><input type="date" placeholder="Date" class="mb-2 shadow" id="trendsDate1">
        </div>
        <div class="col-12 mt-5 ">
          <h5>Daily Caffeine Intake</h5>
        </div>
        <div class="col-12 shadow m-3 mt-0 mr-3">
          <div>
            <canvas id="averageCafChart"></canvas>
          </div>
        </div>
        <div class="col-12 mt-5 ">
          <h5>Favorite Caffeinated Substances</h5>
        </div>
        <div class="col-12 shadow m-3 mb-5 mr-3">
          <div>
            <canvas id="favoriteDrinkChart"></canvas>
          </div>
        </div>
      </div>
      <div class="row" id="myAccountRow" style="display:none">
        <!--<div class="col-xs-4 shadow mb-5 d-flex justify-content-center">
          <form class="m-3">
            <div class="form-group row">
              <div class="col-10">
                <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
              </div>
            </div>
            <div class="form-group row">
              <div class="col-10">
                <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
              </div>
            </div>
            <div class="form-group row">
              <div class="col-10">
                <button type="submit" class="btn btn-primary">Sign in</button>
              </div>
              <div class="col-10 mt-1">
                <button type="submit" class="btn btn-secondary">Create Account</button>
              </div>
            </div>
          </form>
        </div>-->
      </div>
      <div class="row mt-5 m-1 shadow"><h1 style="height:100px;">Advertisment Space</h1></div>
    </div>
    <!-- import jquery, popper.js, boostrap js plugins, script.js-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="/static/script.js" defer></script>
  </body>
</html>

djangonautic/templates/signup_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Accounts</title>
        <link rel="stylesheet" href="{% static 'oldStyles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="https://cdn.glitch.com/d959f5b2-4107-480c-a30a-4ab5f8968f79%2Fcoffee_cup%20(2).png?1558547562811" alt="coffee cup" height="50px"></a></h1>
            <nav>
              <ul>
                {% if user.is_authenticated %}
                  <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                      {% csrf_token %}
                      <button type="submit">Logout</button>
                    </form>
                  </li>
                {% else %}
                  <li> <a href="{% url 'accounts:login' %}">Login</a></li>
                  <li> <a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
              </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>